name: Trigger All Workflows  # 主要工作流的名称

on:
  workflow_dispatch:  # 手动触发：通过 GitHub UI 来触发
  schedule:
     - cron: 0 18 * * *  # 北京时间凌晨2点，定时触发（取消注释并设置时间）

jobs:
    Arthur-Athena-Master:
     uses: ./.github/workflows/Arthur&Athena-Master.yml  # 引用工作流文件：Arthur&Athena-Master.yml

    Arthur-Athena-Stable:
     uses: ./.github/workflows/Arthur&Athena-Stable.yml  # 引用工作流文件：Arthur&Athena-Stable.yml

    Taiyi-Master:
     uses: ./.github/workflows/Taiyi-Master.yml  # 引用工作流文件：Taiyi-Master.yml

    Taiyi-Stable:
     uses: ./.github/workflows/Taiyi-Stable.yml  # 引用工作流文件：Taiyi-Stable.yml

    Delete-Old-Workflows:
     uses: ./.github/workflows/Delete-Old-Workflows.yml  # 引用工作流文件：Delete-Old-Workflows.yml
